server:
  port: 8080

spring:
  application:
    name: emby-mvp-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/emby_mvp
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password:

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

app:
  jwt:
    secret: "change-this-to-a-very-long-random-secret-key"
    expire-seconds: 86400
  media:
    root-path: "E:/Media"
    poster-dir: "E:/Media/.posters"
    actor-dir: "E:/Media/actors"
  tmdb:
    api-key: "311bdcf1ab590070fca59909a8dac778"
    image-base-url: "https://image.tmdb.org/t/p/w500"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
